#!/bin/bash

file=$1

if [ -z "$file" ]; then
	echo "filename not specified"
	exit 1
fi

if [ ! -e "$file" ]; then
	echo "$file not found"
	exit 1
fi

sed -i '/^$/d' "$file"

cat "$file" | tr [:lower:] [:upper:] > "$file.tmp"
mv "$file.tmp" "$file"
